---
- name: Check Disk Space
  hosts: all
  tasks:
    - name: Gather disk space information
      ansible.builtin.disk_usage:
      register: disk_info
 
    - name: Print disk space information
      ansible.builtin.debug:
        msg: "{{ item.item }}"
      loop: "{{ disk_info.ansible_facts.disk_usage }}"
      loop_control:
        label: "{{ item.device }}"
