---
- name: diskspace_mornitor
  hosts: local
  user: root
  gather_facts: no
  vars:
   path: /home/devops

  tasks:
  - name: check diskspace
    shell: "df -hP|awk 'NR>1 && int($5) > 30'"
    register: check_out
  - debug: msg="disk space {{check_out.stdout}}"
